language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install coveralls tox

script:
  - tox -e $TOX_ENV
  - python setup.py check -r

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=pypy
  - TOX_ENV=pypy3

after_success:
  - coveralls --verbose

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: pypy
      env: TOX_ENV=pypy
    - python: pypy3
      env: TOX_ENV=pypy3
